AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Rails:
  Enabled: false
Rails/ActionFilter:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# Since we are unlikely to ever
# generate docs for this project.
Style/Documentation:
  Enabled: false

# If/unless modifier clauses, or
# conditionals (&&/||) are often
# less readable than one-line
# if/unless bodies.
Style/IfUnlessModifier:
  Enabled: false

# See Style/IfUnlessModifier
Style/WhileUntilModifier:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false
